--!strict

local Traits = {
	none = {
		id = "none",
		displayName = "None",
		weight = 88,
		multiplier = 1,
	},
	flawless = {
		id = "flawless",
		displayName = "Flawless",
		weight = 6,
		multiplier = 1.5,
	},
	prismatic = {
		id = "prismatic",
		displayName = "Prismatic",
		weight = 3,
		multiplier = 1.8,
	},
	celestial = {
		id = "celestial",
		displayName = "Celestial",
		weight = 1.5,
		multiplier = 2,
	},
	radiant = {
		id = "radiant",
		displayName = "Radiant",
		weight = 0.8,
		multiplier = 2.35,
	},
	void_touched = {
		id = "void_touched",
		displayName = "Void-Touched",
		weight = 0.2,
		multiplier = 3,
	},
}

return Traits
