--!strict

local RemoteNames = {
	RequestBuyGeode = "RequestBuyGeode",
	RequestPlaceGeode = "RequestPlaceGeode",
	RequestCrackGeode = "RequestCrackGeode",
	RequestOpenGeode = "RequestCrackGeode",
	RequestClaimFinishedGeode = "RequestClaimFinishedGeode",
	RequestPlaceStation = "RequestPlaceStation",
	RequestMovePlacedObject = "RequestMovePlacedObject",
	RequestUpgradeStation = "RequestUpgradeStation",
	RequestClaimDailyReward = "RequestClaimDailyReward",
	RequestCollectOfflineRewards = "RequestCollectOfflineRewards",
	GetInitialState = "GetInitialState",
	StateUpdated = "StateUpdated",
	ShopRotationUpdated = "ShopRotationUpdated",
	RareRevealAnnounced = "RareRevealAnnounced",
	RareGeodeAnnounced = "RareRevealAnnounced",
}

return RemoteNames

